### ISSUE TITLE
Game Engine runs but content not displayed

### ISSUE THREAD

**Issue by devarajan** [leafo/aroma#1]
Hi,

I was just tying out the hello  world program from the aroma site. I got the game engine running, but nothing displayed in inside the game container. 

Enabled the flag Native Client for local testing
Host-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.168 Safari/535.19

WebServer: Apache 2.2.11

Is there some issue? or am I doing something wrong?

Deva

**Comment by leafo** [comment]
There was an issue with the default loader that I just fixed. I just pushed version 0.0.2. Try downloading it and seeing if it fixes the problem.

Thanks

**Comment by devarajan** [comment]
yeah! works perfectly now!

Will play with other functionalites :)

Good Job!
